Add recipe for getting infeasible constraints
scipopt/PySCIPOpt pull request #857
Opened 2024-05-28 13:32 UTC by Joao-Dionisio

Adds slack variables to the constraints and minimizes their sum. Non-zero slack variables correspond to infeasible constraints.

This is still far from Gurobi's Irreducible Inconsistent Subsystem. Take the following constraints:

``` 
x <= 3
x <= 4
x <= 5
x == 7
``` 

This function would return $4$ infeasible constraints, even though it is natural to take ```x == 7``` as the constraint yielding the infeasibility.

2024-05-31 13:38 UTC, Opt-Mucca commented
As I said in the meeting: My suggestion is to add an option to attach a binary variable to each slack variable. If the slack variable is non-zero then force the binary to 1 and minimise the sum of binaries. (This is going to be a behemoth of a model to solve, but would give a minimum amount of constraints that are forced to be invalid).

2024-06-05 17:15 UTC, Joao-Dionisio commented
Thanks for the review @Opt-Mucca, I think it's done now.

 The logical constraint was a bit more complicated than I realized, so I turned to OR SE (https://or.stackexchange.com/q/12142/5352) and implemented Erwin Kalvelagen's answer (who gracefully allowed me to use it).

2024-06-06 14:19 UTC, Opt-Mucca commented
Can you answer or resolve the older questions?

Two points for the current state:
- Why do you need the binary variables? They are created but never used, only the `aux_binaries` are.
- Make sure to remove the old objective function, otherwise you won't get an honest answer on the number of infeasible constraints.

2024-06-06 14:36 UTC, Joao-Dionisio commented
@Opt-Mucca the binary variables are used in line 29. The formulation is not trivial to me, that's why I point to https://or.stackexchange.com/q/12142/5352.

Oops! Good catch on the objective function Mark.

2024-06-14 09:45 UTC, Opt-Mucca requested changes

2024-06-14 09:47 UTC, Joao-Dionisio commented on src/pyscipopt/recipes/infeasibilities.py
> +    model.setEmphasis(SCIP_PARAMEMPHASIS.PHASEFEAS) # focusing on model feasibility
Yeah, but this is incorrect. It could mark feasible models as infeasible, I removed it.

2024-06-14 09:49 UTC, Opt-Mucca commented on src/pyscipopt/recipes/infeasibilities.py
> +        aux_binary[c.name] = model.addVar(ub=1)
Make this binary (should maybe help with performance)

2024-06-14 10:18 UTC, Joao-Dionisio commented
I think that's it @Opt-Mucca!

2024-06-14 12:59 UTC, Opt-Mucca commented
Am happy after our discussion!

2024-06-14 13:02 UTC, merged