Add documentation for event handlers
scipopt/PySCIPOpt pull request #898
Opened 2024-09-11 13:31 UTC by mmghannam

2024-09-11 14:40 UTC, Opt-Mucca requested changes
The only change I'd suggest is splitting the second subsection into multiple subsections. Something like:
"What is an event handler?"
"Adding Event Handlers with Callbacks"
"Add Event Handler Classes"

2024-09-11 14:40 UTC, Opt-Mucca commented on docs/tutorials/eventhandler.rst
> +==============
I'm never sure on this, but I think you should have at least as many "=" characters as there are in the section titles

2024-09-11 14:41 UTC, Opt-Mucca commented
I am super happy to see you already building on the documentation! 
I'm a bit picky on this one because I don't see us changing stuff regularly here once it's added here.

2024-09-11 15:40 UTC, mmghannam commented on docs/tutorials/eventhandler.rst
> +.. code-block:: python
yup you're right, done!

2024-09-11 15:44 UTC, mmghannam commented
> I am super happy to see you already building on the documentation!

You've made it quite smooth to add on the structure you've built so thank you! 

> I'm a bit picky on this one because I don't see us changing stuff regularly here once it's added here.

No worries, pick all you want 😄 anything that's going to make it a better experience for users I'm all for, and thanks for the quick review!

2024-09-12 07:56 UTC, Opt-Mucca approved these changes

2024-09-12 07:56 UTC, Opt-Mucca commented
We have liftoff!

2024-09-12 07:56 UTC, merged