Update tutorial to include parameter emphasis and setting
scipopt/PySCIPOpt pull request #909
Opened 2024-10-02 14:16 UTC by Joao-Dionisio

Fix #908

2024-10-02 17:04 UTC, mmghannam commented
Thanks a lot @Joao-Dionisio! Content-wise looks great, I'm just having trouble compiling the docs at the moment :/

2024-10-03 23:40 UTC, Joao-Dionisio commented
You're using `sphinx-build docs docs/_build` in the root folder, right, @mmghannam? It works on my machine at least.

2024-10-04 09:33 UTC, Opt-Mucca requested changes

2024-10-04 09:34 UTC, Opt-Mucca commented
@Joao-Dionisio I like the changes! I just suggested changes for the subsection titles.

2024-10-05 12:08 UTC, Opt-Mucca approved these changes

2024-10-05 12:08 UTC, merged